confirm-before-quit = false

[editor]
program = "neovim"
args = []

[fonts]
size = 12
family = "TX-02"
features = ["zero","calt","liga"]
symbol-map = [
  # powerline & powerline-extras
  {start = "e0b0", end ="e0b3", font-family="JetBrainsMono Nerd Font Mono"},
  {start = "e0b4", end ="e0c8", font-family="JetBrainsMono Nerd Font Mono"},
  {start = "e0cc", end ="e0d4", font-family="JetBrainsMono Nerd Font Mono"},
  {start = "e0ca", end ="e0ca", font-family="JetBrainsMono Nerd Font Mono"},
  # font-awesome
  {start = "f000", end ="f2e0", font-family="JetBrainsMono Nerd Font Mono"},
  {start = "f200", end ="e2a9", font-family="JetBrainsMono Nerd Font Mono"},
  # seti-ui
  {start = "e5fa", end ="e6b1", font-family="JetBrainsMono Nerd Font Mono"},
  # codicons
  {start = "ea60", end ="ebeb", font-family="JetBrainsMono Nerd Font Mono"},
]

[adaptive-theme]
light = "GruvboxLight"
dark = "GruvboxDarkHard"

[window]
mode = "Maximized"
decorations = "Transparent"
macos-use-shadow = true
colorspace = "rec2020"

[navigation]
use-split = false

[bindings]
keys = [
  { key = "k", with = "super", esc = "\u0002p" },
  { key = "t", with = "super", esc = "\u0002c" },
  { key = "d", with = "super", esc = "\u0002i" },
  { key = "1", with = "super", esc = "\u00021" },
  { key = "2", with = "super", esc = "\u00022" },
  { key = "3", with = "super", esc = "\u00023" },
  { key = "4", with = "super", esc = "\u00024" },
  { key = "5", with = "super", esc = "\u00025" },
  { key = "6", with = "super", esc = "\u00026" },
  { key = "7", with = "super", esc = "\u00027" },
  { key = "8", with = "super", esc = "\u00028" },
  { key = "9", with = "super", esc = "\u00029" },
  { key = "d", with = "shift | super", esc = "\u0002u" },
  { key = "tab", with = "control", esc = "\u0002n" },
  { key = "tab", with = "shift | control", esc = "\u0002p" },
]
