# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: dotfiles
builds:
  - skip: true
dockers_v2:
  - images:
      - caarlos0/debug
    tags:
      - latest
      - "{{.Tag}}"
    extra_files:
      - setup
      - bin
      - crush
      - direnv
      - fd
      - fish
      - gh
      - gh-dash
      - ghostty
      - git
      - hammerspoon
      - lua
      - nvim
      - rio
      - ssh
      - tmux
changelog:
  sort: asc
  use: github
  divider: "---"
  groups:
    - title: "macOS"
      regexp: "^.*\\((darwin|macos)\\):+.*$"
      order: 201
    - title: "Linux"
      regexp: "^.*\\((linux)\\):+.*$"
      order: 202
    - title: "Coding"
      regexp: "^.*\\((git|vim|nvim|neovim)\\):+.*$"
      order: 240
    - title: "Terminals"
      regexp: "^.*\\((kitty|tmux|wezterm|rio|ghostty|alacritty)\\):+.*$"
      order: 250
    - title: "System"
      regexp: "^.*\\((system|fish|fzf|ssh|core|pkg|pkgs|brew)\\):+.*$"
      order: 100
    - title: "AI"
      regexp: "^.*\\(ai|crush\\):+.*$"
      order: 500
    - title: Others
      order: 999
