tap "caarlos0/tap"
tap "charmbracelet/tap"
tap "dagger/tap"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "nikitabobko/tap"
tap "tinygo-org/tools"
brew "bash-completion@2"
brew "btop"
brew "coreutils"
brew "curl"
brew "sqlite"
brew "deno"
brew "entr"
brew "fd"
brew "fish"
brew "fisher"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "go"
brew "go-task"
brew "golangci-lint"
brew "gopls"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "lsd"
brew "lua-language-server"
brew "mas"
brew "moreutils"
brew "neovim"
brew "nmap"
brew "pgcli"
brew "poetry"
brew "pstree"
brew "rio", link: false
brew "ripgrep"
brew "rustup"
brew "scc"
brew "shellcheck"
brew "stern"
brew "stylua"
brew "syft"
brew "tailwindcss"
brew "tailwindcss-language-server"
brew "terminal-notifier"
brew "tmux"
brew "uv"
brew "watch"
brew "wget"
brew "zig"
brew "zoxide"
brew "caarlos0/tap/svu"
brew "charmbracelet/tap/freeze"
brew "charmbracelet/tap/glow"
brew "charmbracelet/tap/gum"
brew "charmbracelet/tap/mods"
brew "charmbracelet/tap/vhs"
brew "dagger/tap/dagger"
brew "tinygo-org/tools/tinygo"
cask "1password"
cask "appcleaner"
cask "claude"
cask "cleanshot"
cask "container"
cask "deckset"
cask "discord"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "goreleaser-pro"
cask "hammerspoon"
cask "imageoptim"
cask "ledger-live"
cask "maccy"
cask "monodraw"
cask "ollama"
cask "orbstack"
cask "rio"
cask "signal"
cask "slack"
cask "soulver"
cask "steam"
cask "telegram"
cask "todoist"
cask "vlc"
cask "whatsapp"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Capture", id: 6458535284
mas "Color Picker", id: 1545870783
mas "Debit & Credit", id: 882637653
mas "HEIC Converter", id: 1294126402
mas "Keynote", id: 409183694
mas "Lungo", id: 1263070803
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Reeder", id: 1529448980
mas "Tailscale", id: 1475387142
mas "Today", id: 6443714928
