tap "caarlos0/tap"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "orlangure/tap"
brew "shellcheck"
brew "actionlint"
brew "alejandra"
brew "sqlite"
brew "ansible"
brew "bash-language-server"
brew "btop"
brew "coreutils"
brew "cosign"
brew "curl"
brew "direnv"
brew "entr"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "go-task"
brew "gofumpt"
brew "golangci-lint"
brew "gopls"
brew "graphviz"
brew "hugo"
brew "hyperfine"
brew "imagemagick"
brew "ipcalc"
brew "jj"
brew "jq"
brew "kubectx"
brew "kubernetes-cli"
brew "lsd"
brew "lua-language-server"
brew "mas"
brew "mole"
brew "moreutils"
brew "tree-sitter"
brew "neovim"
brew "nmap"
brew "pgcli"
brew "prettier"
brew "pstree"
brew "python-lsp-server"
brew "ripgrep"
brew "rust-analyzer"
brew "rustup"
brew "scc"
brew "shfmt"
brew "sshpass"
brew "stern"
brew "stylua"
brew "syft"
brew "taplo"
brew "telnet"
brew "tree-sitter-cli"
brew "typescript-language-server"
brew "vscode-langservers-extracted"
brew "watch"
brew "wget"
brew "yaml-language-server"
brew "zoxide"
brew "orlangure/tap/gocovsh"
cask "appcleaner"
cask "caffeine"
cask "cleanshot"
cask "copilot-cli"
cask "deckset"
cask "discord"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "goreleaser/tap/goreleaser-pro"
cask "hammerspoon"
cask "imageoptim"
cask "ledger-wallet"
cask "goreleaser/tap/mcp"
cask "microsoft-teams"
cask "monodraw"
cask "orbstack"
cask "caarlos0/tap/pinata"
cask "rio"
cask "slack"
cask "soulver"
cask "caarlos0/tap/svu"
cask "telegram"
cask "vlc"
cask "whatsapp"
mas "Azure VPN Client", id: 1553936137
mas "Consent-O-Matic", id: 1606897889
mas "Control Panel for Twitter", id: 1668516167
mas "Control Panel for YouTube", id: 6478456678
mas "Debit & Credit", id: 882637653
mas "HEIC Converter", id: 1294126402
mas "Infuse", id: 1136220934
mas "Keynote", id: 361285480
mas "Lungo", id: 1263070803
mas "Numbers", id: 361304891
mas "Okta Verify", id: 490179405
mas "Pages", id: 361309726
mas "Parcel", id: 375589283
mas "Reeder", id: 1529448980
mas "StopTheMadness", id: 1376402589
mas "Tailscale", id: 1475387142
mas "Vimari", id: 1480933944
