#!/bin/bash
set -euo pipefail

link() {
  mkdir -p "$(dirname "$2")"
  if [ -e "$2" ]; then
    echo "Skipping $2, already exists."
  else
    ln -sf "$1" "$2"
    echo "Linked $1 to $2"
  fi
}

# bins
link $PWD/bin ~/.bin

# tmux
if [ -d ~/.config/tmux/plugins/tpm ]; then
  echo "Skipping TPM, already installed."
else
  mkdir -p ~/.config/tmux/plugins
  git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
fi
link $PWD/tmux/tmux.conf ~/.config/tmux/tmux.conf
tmux source ~/.config/tmux/tmux.conf

# shell
link $PWD/fish/* ~/.config/fish/

# terms
link $PWD/ghostty/config ~/.config/ghostty/config

# ssh
link $PWD/ssh/* ~/.ssh/

# neovim
link $PWD/nvim ~/.config/nvim
nvim --headless "+Lazy! sync" +qa &>/dev/null

# other apps
link $PWD/.editorconfig ~/.editorconfig
link $PWD/hammerspoon/init.lua /Users/carlos/.hammerspoon/init.lua
link $PWD/git/config ~/.config/git/config
link $PWD/git/gitignore ~/.config/git/ignore
link $PWD/gh/config.yml ~/.config/gh/config.yml
link $PWD/gh-dash/config ~/.config/gh-dash/config.yml
link $PWD/fd/ignore ~/.config/fd/ignore

if [[ $OSTYPE == 'darwin'* ]]
    then
    brew bundle
    fi
