# https://taskfile.dev

version: "3"

vars:
  HOSTNAME:
    sh: "hostname | cut -f1 -d'.'"

tasks:
  release:
    vars:
      TAG:
        sh: "date +%Y.%m.%d"
    cmds:
      - "git tag -m {{.TAG}} {{.TAG}}"
      - "git push --tags"
      - "goreleaser release --clean"
  update:
    cmds:
      - nix flake update
  tmux:
    cmds:
      - tmux source ~/.config/tmux/tmux.conf
  apply:
    cmds:
      - task: nixos
      - task: darwin
  nixos:
    status:
      - "test $(uname -s) != Linux"
    cmds:
      - sudo nixos-rebuild switch --flake .#
  darwin:
    status:
      - "test $(uname -s) != Darwin"
    cmds:
      - nix build './#darwinConfigurations.{{ .HOSTNAME }}.system'
      - ./result/sw/bin/darwin-rebuild switch --flake .
  clean:
    cmds:
      - nix-collect-garbage -d
