on:
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --show-trace
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# stolen from https://github.com/nekowinston/dotfiles/blob/main/.github/workflows/check.yml
