# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# stolen from https://github.com/nekowinston/dotfiles/blob/main/.github/workflows/check.yml

on:
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --show-trace
